# Generated by Django 5.2.1 on 2025-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalventa',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta Crédito'), ('TD', 'Tarjeta Débito'), ('TR', 'Transferencia'), ('OT', 'Otro')], default='EF', max_length=2),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta Crédito'), ('TD', 'Tarjeta Débito'), ('TR', 'Transferencia'), ('OT', 'Otro')], default='EF', max_length=2),
        ),
    ]
